stages:
  - build

build and deploy container:
  stage: build
  script:
    - docker stop back && docker rm back && docker rmi back
    - docker build --no-cache --tag back .
    - docker run --name back -p 8080:80 -d back
  tags:
    - vetas-106
  only:
    - rc_test@LifeIT/vetas/backend
