stages:
  - build
  - deploy

default:
  tags: 
    - $RUNNER


build container:
  stage: build
  image: "${DOCKERHUB_URL}/docker:20.10"
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - DOCKER_BUILDKIT=1 docker build --no-cache --build-arg DOCKERHUB_URL=$DOCKERHUB_URL --build-arg APT_MIRROR=$APT_MIRROR --build-arg DEPLOY_ENV=$DEPLOY_ENV --progress=plain -f cicd/Dockerfile -t $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG
    - echo DEVOPS=$DEVOPS > build.env
    - echo DOCKER_IMAGE_FULL_NAME=$CI_REGISTRY_IMAGE:$DOCKER_IMAGE_TAG > build.env
  variables:
    DOCKER_IMAGE_TAG: "realese"
  artifacts:
    reports:
      dotenv: build.env
  tags:
    - $RUNNER
  only:
    - realese
    - main

deploy:
  stage: deploy
  script:
    - curl --request POST
      --form "token=$CI_JOB_TOKEN"
      --form "ref=$DEPLOY_REF"
      --form "variables[PARENT]=backend"
      --form "variables[ENV]=$DEPLOY_ENV"
      --form "variables[DOCKER_IMAGE_FULL_NAME]=$DOCKER_IMAGE_FULL_NAME"
      "$DEVOPS_TRIGGER"
  when: on_success
  only:
    - realese
    - main
