<?php

namespace app\modules\asur\models;

use app\models\db\asur\Task;
use app\models\db\asur\TaskLog;
use app\modules\asur\components\LocalDocumentStorage;
use app\modules\asur\components\RemoteDocumentStorage;
use yii\base\Model;
use yii\helpers\BaseFileHelper;

/**
 * Class CoordinateSendTaskStatusesMessage
 * @package app\modules\asur\models
 */
class CoordinateSendTaskStatusesMessage extends Model
{
    const
        RESULT_TYPE_POSITIVE = 'PositiveAnswer',
        RESULT_TYPE_NEGATIVE = 'NegativeAnswer',
        RESULT_TYPE_ERROR    = 'Error',

        STATUS_ERROR = 1002,
        STATUS_IN_PROCESS = 1003,
        STATUS_RESULT = 1004,
        STATUS_NOT_FOUND = 1005,
        STATUS_REQUEST_ERROR = 1006,
        STATUS_SERVICE_UNAVAILABLE = 1007,
        STATUS_EXPIRED = 1008,
        STATUS_FORBIDDEN = 1009
    ;

    /** @var array  */
    protected $statusInProcess = [self::STATUS_IN_PROCESS, self::STATUS_SERVICE_UNAVAILABLE];

    /**
     * @var array
     */
    protected $statusFinished = [
        self::STATUS_ERROR, self::STATUS_RESULT, self::STATUS_NOT_FOUND, self::STATUS_REQUEST_ERROR,
        self::STATUS_EXPIRED, self::STATUS_FORBIDDEN
    ];

    /** @var Task */
    private $task;

    /** @var array */
    public $data;

    /** @var string */
    public $messageId;

    /** @var string */
    public $taskId;

    /** @var array */
    public $statusCode;

    /** @var string */
    public $statusNote;

    /**
     * @throws \Exception
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        if (!isset($this->data['CoordinateSendTaskStatusesMessage']) ||
            !isset($this->data['CoordinateSendTaskStatusesMessage']['CoordinateTaskStatusDataMessage'])
        ) {
            throw new \Exception('Невозможно обработать сообщение. Не найден блок CoordinateTaskStatusDataMessage');
        }

        $data = $this->data['CoordinateSendTaskStatusesMessage']['CoordinateTaskStatusDataMessage'];

        $this->messageId = (isset($data['MessageId'])) ? $data['MessageId'] : null;
        $this->taskId = (isset($data['TaskId'])) ? $data['TaskId'] : null;
        $this->statusCode = (isset($data['Status']) && isset($data['Status']['StatusCode']))
            ? $data['Status']['StatusCode'] : null;
        $this->statusNote = (isset($data['StatusNote'])) ? $data['StatusNote'] : '';
    }

    public function rules()
    {
        return [
            [
                ['messageId', 'taskId', 'statusCode'],
                'required',
                'message' => 'Не передан {attribute}'
            ],
            [
                'statusCode', 'in', 'range' => [
                    self::STATUS_ERROR, self::STATUS_IN_PROCESS, self::STATUS_RESULT, self::STATUS_NOT_FOUND,
                    self::STATUS_REQUEST_ERROR, self::STATUS_SERVICE_UNAVAILABLE, self::STATUS_EXPIRED,
                    self::STATUS_FORBIDDEN
                ],
                'message' => 'Неизвестный статус сообщения'
            ],
            [
                'data', function ($attribute, $params, $validator) {
                    if (!$this->getTask()) {
                        $this->addError($attribute, 'Не найдена запись с заданными MessageId и TaskId');
                    }
                }
            ]
        ];
    }

    /**
     * @throws \Exception
     */
    public function process()
    {
        if (!$this->validate()) {
            throw new \Exception("Ошибка обработки сообщения:\r\n" .
                implode("\r\n", $this->getErrorSummary(true)));
        }

        switch ($this->statusCode) {
            // ошибки
            case self::STATUS_ERROR:
            case self::STATUS_NOT_FOUND:
            case self::STATUS_REQUEST_ERROR:
            case self::STATUS_EXPIRED:
            case self::STATUS_FORBIDDEN:
                return $this->handleError();

            // промежуточные статусы
            case self::STATUS_IN_PROCESS:
            case self::STATUS_SERVICE_UNAVAILABLE:
                return $this->handleInWork();

            // результат
            case self::STATUS_RESULT:
                return $this->handleResult();
        }

        $this->log();
    }

    /**
     *
     */
    protected function log()
    {
        \Yii::info(
            "{$this->task->message_id}|{$this->task->task_id}|{$this->task->task_number}: {$this->statusCode}, {$this->statusNote}",
            'asur'
        );

        $log = new TaskLog([
            'task_id' => $this->task->id,
            'status_code' => $this->statusCode,
            'status_note' => $this->statusNote
        ]);
        $log->save(false);
    }

    /**
     * @return Task|null|static
     */
    protected function getTask()
    {
        if (!isset($this->task)) {
            $this->task = Task::findOne(['message_id' => $this->messageId, 'task_id' => $this->taskId]);
        }

        return $this->task;
    }

    /**
     *
     */
    protected function handleError()
    {
        $this->task->status = Task::STATUS_ERROR;
        $this->task->save(false);
    }

    /**
     *
     */
    protected function handleInWork()
    {
        $this->task->status = Task::STATUS_SENT;
        $this->task->save(false);
    }

    protected function handleResult()
    {
        $documentId = $this->data['Result']['BinaryView']['CoordinateFile']['FileIdInStore'];

        try {
            $remoteStorage = $this->getRemoteStorage();
            $properties = $remoteStorage->getDocumentProperties($documentId);
            if (!isset($properties['MimeType'])) {
                throw new \Exception('Не удалось определить тип документа');
            }

            $extensions = BaseFileHelper::getExtensionsByMimeType($properties['MimeType']);
            if (empty($extensions)) {
                throw new \Exception('Неизвестный тип документа');
            }
            $ext = $extensions[0];
            $fileName = "{$documentId}.{$ext}";
            $document = $remoteStorage->getDocument($documentId);
            $this->getLocalStorage()->save($fileName, $document);

            $this->task->status = Task::STATUS_FINISHED;
        } catch (\Exception $e) {
            \Yii::error($e->getMessage(), 'asur');
        }

    }

    /**
     * @return RemoteDocumentStorage
     */
    public function getRemoteStorage()
    {
        return \Yii::$app->getModule('asur')->remoteStorage;
    }

    /**
     * @return LocalDocumentStorage
     */
    public function getLocalStorage()
    {
        return \Yii::$app->getModule('asur')->localStorage;
    }

}
