<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 24.04.19
 * Time: 13:47
 */

namespace app\modules\admin\controllers\statistics;

use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\BalanceFlow;
use app\modules\admin\models\export\BalanceReportExport;
use app\modules\admin\models\Organization;
use DateTime;
use Yii;
use yii\db\Expression;

class BalanceTmcReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;

    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id_organization', []);
        if (empty($this->from)) {
            $date = new DateTime(date("Y") . '-01-01');
            $this->from = $date->format('Y-m-d');
        }
        if (empty($this->to)) {
            $date = new DateTime();
            $this->to = $date->format('Y-m-d');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function buildQuery($from, $to, $organizations)
    {
        $mainQuery = BalanceFlow::find()
            ->select([
                'balance_drugs.id',
                'balance_drugs.id_organization',
                'organizations.parent_id',
                'organizations.short_name',
                'fias_addresses.id_area',
                '"areas"."name" as area_name',
                '"drugs"."name" as drug_name',
                'drugs.id_measure',
                'measures.name',
                'organizations_tree.path',
                new Expression('SUM(case when "balance_flow"."created_at"::date < :from then case when balance_flow.flow_type = \'income\' then count else -count end else 0 end) as balancePeriodStart', [':from' => $from]),
                new Expression('SUM(case when "balance_flow"."created_at"::date BETWEEN :from AND :to then case when balance_flow.flow_type = \'income\' then count end else 0 end) as got', [':from' => $from, ':to' => $to]),
                new Expression('SUM(case when "balance_flow"."created_at"::date BETWEEN :from AND :to then case when balance_flow.flow_type = \'expense\' then count end else 0 end) as spent', [':from' => $from, ':to' => $to]),
                new Expression('SUM(case when "balance_flow"."created_at"::date <= :to then case when balance_flow.flow_type = \'income\' then count else -count end else 0 end) as balancePeriodEnd', [':to' => $to])
            ])
            ->joinWith(['balanceDrug.drug', 'organization', 'organization.fias_addresses'], false)
            ->leftJoin('public.organizations_tree', ['organizations_tree.id' => new Expression('organizations.id')])
            ->leftjoin('measures', ['measures.id' => new Expression('drugs.id_measure')])
            ->leftjoin('areas', ['areas.id' => new Expression('fias_addresses.id_area')])
            ->groupBy([
                'balance_drugs.id',
                'organizations.id',
                'organizations.parent_id',
                'organizations.short_name',
                'fias_addresses.id_area',
                'drug_name',
                'area_name',
                'measures.name',
                'drugs.id_measure',
                'organizations_tree.path'
            ])
            ->orderBy([
                'areas.name' => SORT_ASC,
                'organizations.short_name' => SORT_ASC,
                'drugs.name' => SORT_ASC,
            ])
            ->asArray();

        $sql = '
WITH RECURSIVE org_tree AS (
	(SELECT
		"organizations"."id", 
		"organizations"."parent_id", 
		SUM(case when "balance_flow"."created_at"::date <  :from then case when balance_flow.flow_type = \'income\' then count else -count end else 0 end) as balancePeriodStart, 
		SUM(case when "balance_flow"."created_at"::date BETWEEN :from AND :to then case when flow_type = \'income\' then count end else 0 end) as got, 
		SUM(case when "balance_flow"."created_at"::date BETWEEN :from AND :to then case when flow_type = \'expense\' then count end else 0 end) as spent, 
		SUM(case when "balance_flow"."created_at"::date <= :to then case when balance_flow.flow_type = \'income\' then count else -count end else 0 end) as balancePeriodEnd,
		0 as totalStart,
		0 as totalGot,
		0 as totalSpent,
		0 as totalEnd 
	FROM "balance_drugs"
	LEFT JOIN "balance_flow" ON "balance_drugs"."id" = "balance_flow"."id_balance_tmc_type" AND "balance_flow"."balance_tmc_type" = \'drug\'
	LEFT JOIN "drugs" ON "balance_drugs"."id_drug" = "drugs"."id"
	LEFT JOIN "public"."organizations" ON "balance_flow"."id_organization" = "public"."organizations"."id" 
	LEFT JOIN "fias_addresses" ON "public"."organizations"."id_fias_address" = "fias_addresses"."id" 
	LEFT JOIN "public"."organizations_tree" ON "organizations_tree"."id"=organizations.id 
	LEFT JOIN "measures" ON "measures"."id"=drugs.id_measure 
	LEFT JOIN "areas" ON "areas"."id"=fias_addresses.id_area 
    GROUP BY 
		"balance_drugs"."id_drug",
		"drugs"."name", 
		"organizations"."id", 
		"organizations"."parent_id", 
		"organizations"."short_name", 	
		"fias_addresses"."id_area", 
		"measures"."name", 
		"organizations_tree"."path" 
	ORDER BY  
		"organizations"."short_name", 
		"drugs"."name")
  UNION ALL
  select 
	o2.id,
        o2.parent_id,
	o1.balancePeriodStart, 
	o1.got, 
	o1.spent, 
	o1.balancePeriodEnd,
        o1.totalStart,
	o1.totalGot,
	o1.totalSpent,
	o1.totalEnd 
  from organizations o2
  inner join org_tree o1 ON o2.id = o1.parent_id
)
SELECT t.id, t.parent_id, SUM(t.balancePeriodStart) as totalStart, SUM(t.got) as totalGot, SUM(t.spent) as totalSpent, SUM(t.balancePeriodEnd) as totalEnd
FROM org_tree t
group by t.id, t.parent_id
order by t.id;';

        $rows = yii::$app->db->createCommand($sql, [
            ':from' => $from,
            ':to' => $to
        ])
            ->queryAll();

        $orderedRows = [];
        foreach ($rows as $row) {
            $orderedRows[$row['id']][] = $row;
        }

        if(!empty($organizations)) {
            $mainQuery->andWhere(['organizations.id' => $organizations]);
        }

        $data = $mainQuery->all();

        $orgs = new Organization;
        $tree = $orgs::orgTreeIds(Organization::GOS_ROOT_ID);

        $orderedData = [];
        $pathOrgs = '';
        foreach ($data as $datum) {
            $orderedData[$datum['id_organization']][] = $datum;
            $pathOrgs .= $datum['path'];
        }
        $pathOrgs = array_unique(explode('/', $pathOrgs)); //собираем массив организаций, которые хоть раз появляются в path любой организации для отрисовки иерархии

        $output = [$data, $pathOrgs, $orderedRows, $orderedData, $tree];
        return $output;
    }

    public function actionIndex()
    {
        $data = $this->buildQuery($this->from, $this->to, $this->organizations)[0];
        $pathOrgs = $this->buildQuery($this->from, $this->to, $this->organizations)[1];
        $orderedRows = $this->buildQuery($this->from, $this->to, $this->organizations)[2];
        $orderedData = $this->buildQuery($this->from, $this->to, $this->organizations)[3];
        $tree = $this->buildQuery($this->from, $this->to, $this->organizations)[4];

        return $this->render('index', [
            'data' => $data,
            'pathOrgs' => $pathOrgs,
            'orderedRows' => $orderedRows,
            'orderedData' => $orderedData,
            'tree' => $tree
        ]);
    }

    public function actionExport()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations);
        $exportedReport = new BalanceReportExport();
        $exportedReport->export($mainQuery, "Отчет по использованию препаратов c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}