<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 21.06.19
 * Time: 11:19
 */

namespace app\modules\admin\controllers\statistics;

use app\common\models\VisitStatus;
use app\models\db\BalanceEquipments;
use app\models\db\VisitServiceTmc;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\CapacityReportExport;
use DateTime;
use yii\db\Expression;

/**
 * Class CapacityReportController
 * @package app\modules\admin\controllers\statistics
 */
class CapacityReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;

    /**
     * @throws \Exception
     */
    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id_organization', []);
        if (empty($this->from)) {
            $date = new DateTime(date("Y") . '-01-01');
            $this->from = $date->format('Y-m-d');
        }
        if (empty($this->to)) {
            $date = new DateTime();
            $this->to = $date->format('Y-m-d');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $from
     * @param $to
     * @param $organizations
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord[]
     */
    public function buildQuery($from, $to, $organizations) {
        $mainQuery = BalanceEquipments::find()
            ->select([
                'balance_equipments.id',
                'visit_service_tmc.id_organization',
                'visit_service_tmc.name',
                'visit_service_tmc.entity_type',
                'sum(count)',
                'organizations.short_name',
            ])
            ->andWhere([
                'or',
                ['entity_type' => VisitServiceTmc::TYPE_BALANCE_EQUIPMENTS],
                ['entity_type' => VisitServiceTmc::TYPE_EQUIPMENT]])
            ->andWhere(['between', new Expression('coalesce("visits"."fact_start_dttm"::date, lower("visits"."time_range")::date, "visits"."created_at"::date)'), $from, $to])
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->joinWith([
                'visitServiceTmcs',
                'visitServiceTmcs.visit',
                'organization'
            ], false)
            ->groupBy([
                'balance_equipments.id',
                'visit_service_tmc.id_organization',
                'visit_service_tmc.name',
                'organizations.id',
                'visit_service_tmc.entity_type'
            ])
            ->orderBy([
                'organizations.short_name' => SORT_ASC,
                'visit_service_tmc.name' => SORT_ASC,
            ])
            ->asArray();

        if (!empty($organizations)) {
            $mainQuery->andWhere(['organizations.id' => $organizations]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    /**
     * @return string
     */
    public function actionIndex() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations);
        return $this->render('index', [
            'data' => $mainQuery,
        ]);
    }

    /**
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionExport()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations);
        $exportedReport = new CapacityReportExport();
        $exportedReport->export($mainQuery, "Отчет о загрузке мощностей c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}