<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 20.03.19
 * Time: 14:43
 */

namespace app\modules\admin\controllers\statistics;

use app\common\models\VisitStatus;
use app\models\db\ShiftType;
use app\models\db\VisitsGovServices;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\ClinicsDutyReportExport;
use app\modules\admin\models\Organization;
use app\modules\admin\models\Visits;
use yii\db\Expression;

/**
 * Class ClinicsDutyReportController
 * @package app\modules\admin\controllers\statistics
 */
class ClinicsDutyReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;
    public $areas;
    public $districts;

    /**
     *
     */
    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id', []);
        $this->areas = \Yii::$app->request->get('id_area', []);
        $this->districts = \Yii::$app->request->get('id_district', []);

        if (empty($this->from)) {
            $this->from = date("Y").'-01-01';
        }
        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $from
     * @param $to
     * @param $organizations
     * @param $areas
     * @param $districts
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord[]
     */
    public function buildQuery($from, $to, $organizations, $areas, $districts) {
        $mosruChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_MOSRU_APPOINTMENT])
            ->scalar();
        $phoneChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_PHONE_APPOINTMENT])
            ->scalar();
        $lqChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_LIVE_QUEUE])
            ->scalar();
        $workdayChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_WORKDAY])
            ->scalar();

        $appointmentVisitsQuery = Visits::find()
            ->select('count(*)')
            ->where([
                'id_organization' => new Expression('organizations.id'),
                'channel' => $workdayChannelId,
            ])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $mosruVisitsQuery = Visits::find()
            ->select('count(*)')
            ->where([
                'id_organization' => new Expression('organizations.id'),
                'channel' => $mosruChannelId
            ])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $phoneVisitsQuery = Visits::find()
            ->select('count(*)')
            ->where([
                'id_organization' => new Expression('organizations.id'),
                'channel' => $phoneChannelId
            ])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $liveQueueVisitsQuery = Visits::find()
            ->select('count(*)')
            ->where([
                'id_organization' => new Expression('organizations.id'),
                'channel' => $lqChannelId
            ])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $totalVisitsQuery = Visits::find()
            ->select('count(*) as total')
            ->where([
                'id_organization' => new Expression('organizations.id')
            ])
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $servicesCounter = VisitsGovServices::find()
            ->select('sum(count)')
            ->joinWith('visit', false)
            ->where([
                'id_visit' => new Expression('visits.id'),
                'visits.id_organization' => new Expression('organizations.id')
            ])
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->andWhere(['between', new Expression('"visits_gov_services"."created_at"::date'), $from, $to]);

        $fromQuery = Organization::find()
            ->select([
                'organizations.id',
                'organizations.short_name',
                'fias_addresses.id_area',
                'areas.name as area_name',
                'fias_addresses.id_district',
                'districts.name as dist_name',
                'mosruVisitsQuery' => $mosruVisitsQuery,
                'phoneVisitsQuery' => $phoneVisitsQuery,
                'liveQueueVisitsQuery' => $liveQueueVisitsQuery,
                'appointmentVisitsQuery' => $appointmentVisitsQuery,
                'totalVisitsQuery' => $totalVisitsQuery,
                'servicesCounter' => $servicesCounter,
            ])
            ->joinWith(['fias_addresses', 'visits'], false)
            ->leftjoin('areas', ['areas.id' => new Expression('fias_addresses.id_area')])
            ->leftjoin('districts', ['districts.id' => new Expression('fias_addresses.id_district')])
            ->groupBy([
                'organizations.id',
                'organizations.short_name',
                'fias_addresses.id_area',
                'areas.name',
                'fias_addresses.id_district',
                'districts.name',
            ])
            ->orderBy([
                'areas.name' => SORT_ASC,
                'districts.name' => SORT_ASC,
                'organizations.short_name' => SORT_ASC,
            ]);

        $mainQuery =  VisitsGovServices::find()
            ->from(['t' => $fromQuery])
            ->andWhere(['>', 't.totalVisitsQuery', 0])
            ->asArray();

        if(!empty($organizations)) {
            $mainQuery->andWhere(['t.id' => $organizations]);
        }
        if(!empty($areas)) {
            $mainQuery->andWhere(['t.id_area' => $areas]);
        }
        if(!empty($districts)) {
            $mainQuery->andWhere(['t.id_district' => $districts]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    /**
     * @return string
     */
    public function actionIndex() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas, $this->districts);
        return $this->render('index', [
            'data' => $mainQuery,
        ]);
    }

    /**
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionExport() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas, $this->districts);
        $exportedReport = new ClinicsDutyReportExport();
        $exportedReport->export($mainQuery, "Отчет о нагрузке на ветеринарные учреждения и службы c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}