<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 01.03.19
 * Time: 15:48
 */

namespace app\modules\admin\controllers\statistics;

use app\common\models\VisitStatus;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\CommonReportExport;
use app\modules\admin\models\Organization;
use app\modules\admin\models\Pets;
use app\modules\admin\models\Visits;
use yii\db\Expression;

/**
 * Class CommonReportController
 * @package app\modules\admin\controllers\statistics
 */
class CommonReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;
    public $areas;

    /**
     *
     */
    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id', []);
        $this->areas = \Yii::$app->request->get('id_area', []);

        if (empty($this->from)) {
            $this->from = date('Y') . '-01-01';
        }

        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $from
     * @param $to
     * @param $organizations
     * @param $areas
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord[]
     */
    public function buildQuery($from, $to, $organizations, $areas) {
        $totalVisitsQuery = Visits::find()
            ->select('count(*)')
            ->where([
                'id_organization' => new Expression('organizations.id')
            ])
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->andWhere(['between', new Expression('"created_at"::date'), '1970-01-01', date('Y-m-d')]);

        $periodVisitsQuery = Visits::find()
            ->select('count(*)')
            ->where([
                'id_organization' => new Expression('organizations.id'),
            ])
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $totalPetsQuery = Pets::find()
            ->select('count(*)')
            ->where([
                'id_reg_organization' => new Expression('organizations.id')
            ])
            ->andWhere(['between', new Expression('"created_at"::date'), '1970-01-01', date('Y-m-d')]);

        $periodPetsQuery = Pets::find()
            ->select('count(*)')
            ->where([
                'id_reg_organization' => new Expression('organizations.id'),
            ])
            ->andWhere(['between', new Expression('"created_at"::date'), $from, $to]);

        $mainQuery = Organization::find()
            ->select([
                'organizations.id',
                'organizations.short_name',
                'fias_addresses.id_area',
                'areas.name',
                'totalPets' => $totalPetsQuery,
                'periodPets' => $periodPetsQuery,
                'totalVisits' => $totalVisitsQuery,
                'periodVisits' => $periodVisitsQuery,
            ])
            ->joinWith(['fias_addresses'], false)
            ->leftjoin('areas', ['areas.id' => new Expression('fias_addresses.id_area')])
            ->asArray()
            ->orderBy([
                'areas.name' => SORT_ASC,
                'organizations.short_name' => SORT_ASC,
            ]);

        if(!empty($organizations)) {
            $mainQuery->andWhere(['organizations.id' => $organizations]);
        }
        if(!empty($areas)) {
            $mainQuery->andWhere(['fias_addresses.id_area' => $areas]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    /**
     * @return string
     */
    public function actionIndex() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas);

        return $this->render('index', [
            'data' => $mainQuery,
        ]);
    }

    /**
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionExport()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas);
        $exportedReport = new CommonReportExport();
        $exportedReport->export($mainQuery, "Краткая статистика организаций c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}