<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 26.03.19
 * Time: 14:12
 */

namespace app\modules\admin\controllers\statistics;

use app\common\models\VisitStatus;
use app\models\db\VisitPrice;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\EmployeesReportExport;
use app\modules\admin\models\VisitsSpecialist;
use yii\db\Expression;

class EmployeesReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;
    public $areas;
    public $specialists;

    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id_organization', []);
        $this->areas = \Yii::$app->request->get('id_area', []);
        $this->specialists = \Yii::$app->request->get('id', []);

        if (empty($this->from)) {
            $this->from = date("Y").'-01-01';
        }
        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function buildQuery($from, $to, $organizations, $areas, $specialists)
    {
        $totalAmountSubQuery = VisitPrice::find()
            ->select([
                new Expression('distinct visits_specialists.id_visit'),
                'visits_specialists.id_specialist',
                'sum(visit_price.price_with_discount) as total',
                'count(visit_price.id_visit)'
            ])
            ->joinWith('visit.specialists', false)
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->andWhere(['between', new Expression('"visits"."created_at"::date'), $from, $to])
            ->groupBy(['visits_specialists.id_visit', 'visits_specialists.id_specialist']);

        $totalAmountQuery = VisitPrice::find()
            ->select([
                'sum(total)',
            ])
            ->from(['tt' => $totalAmountSubQuery])
            ->andWhere(['tt.id_specialist' => new Expression('specialists.id')])
            ->groupBy(['tt.id_specialist']);

        $mainQuery = VisitsSpecialist::find()
            ->select([
                'users.id',
                'specialists.id',
                'users.fullname',
                'specialists.id_organization',
                'fias_addresses.id_area',
                new Expression('count(distinct visits_specialists.id_visit) as total_visits'),
                new Expression('sum(coalesce(visits_gov_services.count, 1)) as total_services'),
                'total_amount' => $totalAmountQuery,
                new Expression('sum(case when visits_gov_services.apply_discount = true and discount.value = 100 then coalesce(visits_gov_services.count, 1) else 0 end) as total_free_services'),
                'areas.name',
                'organizations.short_name'
            ])
            ->joinWith([
                'specialist.user',
                'visits',
                'visits.visitsGovServices',
                'visits.visitPrice',
                'visits.organization.fias_addresses',
                'visits.organization.fias_addresses.area',
                'visits.visitPrice.discount',
            ], false)
            ->groupBy([
                'users.id',
                'specialists.id_organization',
                'specialists.id',
                'fias_addresses.id_area',
                'areas.name',
                'organizations.short_name'
            ])
            ->orderBy([
                'areas.name' => SORT_ASC,
                'organizations.short_name' => SORT_ASC,
                'users.fullname' => SORT_ASC])
            ->andWhere(['visits.status' => VisitStatus::FINISHED])
            ->andWhere(['between', new Expression('"visits"."created_at"::date'), $from, $to])
            ->asArray();

        if(!empty($organizations)) {
            $mainQuery->andWhere(['visits.id_organization' => $organizations]);
        }
        if(!empty($areas)) {
            $mainQuery->andWhere(['fias_addresses.id_area' => $areas]);
        }
        if(!empty($specialists)) {
            $mainQuery->andWhere(['users.id' => $specialists]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    public function actionIndex()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas, $this->specialists);

        return $this->render('index', [
            'data' => $mainQuery,
        ]);
    }

    public function actionExport()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas, $this->specialists);
        $exportedReport = new EmployeesReportExport();
        $exportedReport->export($mainQuery, "Отчет по работе сотрудников c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}