<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 29.05.19
 * Time: 14:49
 */

namespace app\modules\admin\controllers\statistics;

use app\models\db\Areas;
use app\models\db\Districts;
use app\models\db\Pets;
use app\models\db\Species;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\Organization;
use app\modules\admin\models\export\FirstlyRegReportExport;
use yii\db\Expression;

/**
 * Class FirstlyRegReportController
 * @package app\modules\admin\controllers\statistics
 */
class FirstlyRegReportController extends AdminController
{
    public $from;
    public $to;
    public $areas;
    public $districts;
    public $organizations;
    public $species;
    public $organizationsFilter;
    public $areasFilter;
    public $districtsFilter;
    public $speciesFilter;

    /**
     *
     */
    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->areas = \Yii::$app->request->get('id_area');
        $this->districts = \Yii::$app->request->get('id_district');
        $this->organizations = \Yii::$app->request->get('id_reg_organization');
        $this->species = \Yii::$app->request->get('idSpec');
        if (empty($this->from)) {
            $this->from = date('Y-m') . '-01';
        }
        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }

        $this->organizationsFilter = Organization::find()
            ->select('short_name')
            ->orderBy(['name' => SORT_ASC])
            ->indexBy('id')
            ->asArray()
            ->column();
        $this->areasFilter = Areas::find()
            ->select('name')
            ->orderBy(['name' => SORT_ASC])
            ->indexBy('id')
            ->asArray()
            ->column();
        $this->districtsFilter = Districts::find()
            ->select('name')
            ->orderBy(['name' => SORT_ASC])
            ->indexBy('id')
            ->asArray()
            ->column();
        $this->speciesFilter = Species::find()
            ->select('name')
            ->orderBy(['name' => SORT_ASC])
            ->indexBy('id')
            ->asArray()
            ->column();
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $from
     * @param $to
     * @param $areas
     * @param $districts
     * @param $organizations
     * @param $species
     * @return \app\models\db\PetsQuery|array|\yii\db\ActiveQuery|\yii\db\ActiveRecord[]
     */
    public function buildQuery($from, $to, $areas, $districts, $organizations, $species) {
        $mainQuery = Pets::find()
            ->select([
                'pets.id',
                'pet_owners.fullname as ownName',
                new Expression('coalesce(pet_owners.id_fias_address, pet_owners.id_fact_fias_address) as id_fias_address'),
                'ownFias.full_address as ownAddress',
                'contacts.name as ownPhone',
                'pets.name as petName',
                'pets.reg_date',
                'species.id as idSpec',
                'species.name as specName',
                'identification_types.name as identType',
                'pet_identification.identification_code',
                'pets.id_reg_organization',
                'organizations.short_name',
                'organizations.id_fias_address as orgAddress',
                'orgFias.id_area',
                'orgFias.id_district',
                'areas.name as areaName',
                'districts.name as distName'
            ])
            ->joinWith(['owners', 'species', 'pet_identification', 'pet_identification.ident_type', 'regOrganization'], false)
            ->leftJoin('contacts', ['pet_owners.id' => new Expression('contacts.entity_id')])
            ->leftJoin('fias_addresses ownFias', ['ownFias.id' => new Expression('pet_owners.id_fias_address')])
            ->leftJoin('fias_addresses orgFias', ['orgFias.id' => new Expression('organizations.id_fias_address')])
            ->leftJoin('areas', ['orgFias.id_area' => new Expression('areas.id')])
            ->leftJoin('districts', ['orgFias.id_district' => new Expression('districts.id')])
            ->orderBy([
                'areaName' => SORT_ASC,
                'distName' => SORT_ASC,
                'organizations.short_name' => SORT_ASC,
                'specName' => SORT_ASC
            ])
            ->asArray();

        $mainQuery->andWhere(['between', new Expression('"pets"."reg_date"::date'), $from, $to]);
        $mainQuery->andWhere(['pets_to_owner.id_owner_type' => 1]);
        $mainQuery->andWhere(['pet_owners.is_deleted' => FALSE]);
        $mainQuery->andWhere(['or', ['contacts.main_flag' => TRUE], ['contacts.main_flag' =>  null]]);
        $mainQuery->andWhere(['or', ['!=', 'contacts.id_contact_type', 6], ['contacts.id_contact_type' => null]]);
        $mainQuery->andWhere(['or', ['contacts.entity_type' => 'pet_owner'], ['contacts.entity_type' => null]]);

        if(!empty($organizations)) {
            $mainQuery->andWhere(['pets.id_reg_organization' => $organizations]);
        }
        if(!empty($areas)) {
            $mainQuery->andWhere(['orgFias.id_area' => $areas]);
        }
        if(!empty($districts)) {
            $mainQuery->andWhere(['orgFias.id_district' => $districts]);
        }
        if(!empty($species)) {
            $mainQuery->andWhere(['species.id' => $species]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }


    /**
     * @return string
     */
    public function actionIndex() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->areas, $this->districts, $this->organizations, $this->species);
        return $this->render('index', [
            'data' => $mainQuery,
            'organizations' => $this->organizationsFilter,
            'areas' => $this->areasFilter,
            'districts' => $this->districtsFilter,
            'species' => $this->speciesFilter
        ]);
    }

    /**
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionExport() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->areas, $this->districts, $this->organizations, $this->species);
        $exportedReport = new FirstlyRegReportExport();
        $exportedReport->export($mainQuery, "Отчет по первично зарегистрированным владельцам/животным c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}