<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 26.06.19
 * Time: 15:48
 */

namespace app\modules\admin\controllers\statistics;

use app\common\models\VisitStatus;
use app\models\db\ShiftType;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\FullVisitsReportExport;
use app\modules\admin\models\Organization;
use yii\db\Expression;

/**
 * Class FullVisitsReportController
 * @package app\modules\admin\controllers\statistics
 */
class FullVisitsReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;
    public $areas;
    public $districts;
    public $mosruChannelId;
    public $phoneChannelId;
    public $lqChannelId;
    public $workdayChannelId;
    public $params;

    /**
     *
     */
    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id_organization', []);
        $this->areas = \Yii::$app->request->get('id_area', []);
        $this->districts = \Yii::$app->request->get('id_district', []);

        $this->mosruChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_MOSRU_APPOINTMENT])
            ->scalar();
        $this->phoneChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_PHONE_APPOINTMENT])
            ->scalar();
        $this->lqChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_LIVE_QUEUE])
            ->scalar();
        $this->workdayChannelId = ShiftType::find()
            ->select('id')
            ->where(['type' => ShiftType::ASSIGN_SHIFT_TYPE_FOR_WORKDAY])
            ->scalar();

        if (empty($this->from)) {
            $this->from = date("Y")-5 . '-01-01';
        }
        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }

        $this->params = [
            ':from' => $this->from,
            ':to' => $this->to,
            ':mosRu' => $this->mosruChannelId,
            ':phone' => $this->phoneChannelId,
            ':lq' => $this->lqChannelId,
            ':wd' => $this->workdayChannelId,
            ':cancelled' => VisitStatus::CANCELED,
            ':transfered' => VisitStatus::TRANSFER,
            ':finished' => VisitStatus::FINISHED
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $params
     * @return array|\yii\db\ActiveQuery|\yii\db\ActiveRecord[]
     */
    public function buildQuery($params) {
        $mainQuery = Organization::find()
            ->select([
                'organizations.id as id_organization',
                'organizations.short_name',
                'organizations.id_fias_address',
                'fias_addresses.id_area',
                'areas.name as area_name',
                'fias_addresses.id_district',
                'districts.name as dist_name',

                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.channel = :mosRu
                                                    then visits.id else null end) as mos_ru_created', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :cancelled 
                                                    and visits.channel = :mosRu
                                                    then visits.id else null end) as mos_ru_cancelled', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :transfered 
                                                    and visits.channel = :mosRu 
                                                    then visits.id else null end) as mos_ru_transfered', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to  
                                                    and visits.status = :finished 
                                                    and visits.channel = :mosRu 
                                                    then visits.id else null end) as mos_ru_finished', $params),

                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.channel = :phone 
                                                    then visits.id else null end) as phone_created', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :cancelled
                                                    and visits.channel = :phone 
                                                    then visits.id else null end) as phone_cancelled', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :transfered
                                                    and visits.channel = :phone 
                                                    then visits.id else null end) as phone_transfered', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to
                                                    and visits.status = :finished
                                                    and visits.channel = :phone
                                                    then visits.id else null end) as phone_finished', $params),

                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.channel = :lq
                                                    then visits.id else null end) as lq_created', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to
                                                    and visits.status = :cancelled
                                                    and visits.channel = :lq
                                                    then visits.id else null end) as lq_cancelled', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :transfered
                                                    and visits.channel = :lq
                                                    then visits.id else null end) as lq_transfered', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :finished
                                                    and visits.channel = :lq
                                                    then visits.id else null end) as lq_finished', $params),

                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.channel = :wd
                                                    then visits.id else null end) as wd_created', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :cancelled
                                                    and visits.channel = :wd
                                                    then visits.id else null end) as wd_cancelled', $params),
                new Expression('count(case when "visits"."created_at"::date between :from and :to 
                                                    and visits.status = :finished
                                                    and visits.channel = :wd
                                                    then visits.id else null end) as wd_finished', $params),
            ])
            ->joinWith([
                'fias_addresses',
                'fias_addresses.area',
                'fias_addresses.district',
                'visits'
            ], false)
            ->groupBy([
                'organizations.id',
                'fias_addresses.id_area',
                'area_name',
                'fias_addresses.id_district',
                'dist_name'
            ])
            ->orderBy([
                'area_name' => SORT_ASC,
                'dist_name' => SORT_ASC,
                'organizations.short_name' => SORT_ASC
            ])
            ->asArray();

        if(!empty($this->organizations)) {
            $mainQuery->andWhere(['organizations.id' => $this->organizations]);
        }
        if(!empty($this->areas)) {
            $mainQuery->andWhere(['fias_addresses.id_area' => $this->areas]);
        }
        if(!empty($this->districts)) {
            $mainQuery->andWhere(['fias_addresses.id_district' => $this->districts]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    /**
     * @return string
     */
    public function actionIndex() {
        $mainQuery = $this->buildQuery($this->params);
        return $this->render('index', [
            'data' => $mainQuery,
        ]);
    }

    /**
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionExport() {
        $mainQuery = $this->buildQuery($this->params);
        $exportedReport = new FullVisitsReportExport();
        $exportedReport->export($mainQuery, "Общий отчет по приемам c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}