<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 04.03.19
 * Time: 13:06
 */

namespace app\modules\admin\controllers\statistics;

use app\models\db\Pets;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\RegPetsReportExport;

/**
 * Class RegPetsReportController
 * @package app\modules\admin\controllers\statistics
 */
class RegPetsReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;
    public $species;

    /**
     *
     */
    public function init()
    {
        $this->from = \Yii::$app->request->get('from', null);
        $this->to = \Yii::$app->request->get('to', null);
        $this->organizations = \Yii::$app->request->get('id_reg_organization', []);
        $this->species = \Yii::$app->request->get('id_species', []);

        if (empty($this->from)) {
            $this->from = date('Y') . '-01-01';
        }

        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @param $from
     * @param $to
     * @param $organizations
     * @param $species
     * @return \app\models\db\PetsQuery|array|\yii\db\ActiveQuery|\yii\db\ActiveRecord[]
     */
    public function buildQuery($from, $to, $organizations, $species) {
        $mainQuery = Pets::find()
            ->select([
                'pets.id',
                'pets.name as pet_name',
                'pet_identification.id_ident_type',
                'identification_types.name as ident_name',
                'pet_identification.identification_code',
                'pet_owners.fullname',
                'coalesce(pet_owners.id_fias_address, pet_owners.id_fact_fias_address) as owner_address',
                'fias_addresses.full_address',
                'contacts.name as contact_name',
                'pets.reg_date',
                'reg_certificates.number',
                'pets.id_species',
                'species.name as spec_name',
                'pets.id_reg_organization',
                'organizations.short_name'
            ])
            ->joinWith([
                'pet_identification',
                'pet_identification.ident_type',
                'owner',
                'owner.fias_addresses',
                'owner.contacts',
                'reg_certificate',
                'species',
                'regOrganization'
            ], false)
            ->andWhere(['between', 'pets.reg_date', $from, $to])
            ->andWhere(['is not', 'reg_certificates.number', null])
            ->orderBy([
                'organizations.short_name' => SORT_ASC,
                'spec_name' => SORT_ASC,
                'pet_name' => SORT_ASC
            ])
            ->asArray();

        if (!empty($organizations)) {
            $mainQuery->andWhere(['pets.id_reg_organization' => $organizations]);
        }
        if (!empty($species)) {
            $mainQuery->andWhere(['species.id' => $species]);
        }

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    /**
     * @return string
     */
    public function actionIndex() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->species);
        return $this->render('index', [
            'data' => $mainQuery,
        ]);
    }

    /**
     * @throws \PhpOffice\PhpSpreadsheet\Exception
     * @throws \PhpOffice\PhpSpreadsheet\Writer\Exception
     * @throws \yii\web\RangeNotSatisfiableHttpException
     */
    public function actionExport() {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->species);
        $exportedReport = new RegPetsReportExport();
        $exportedReport->export($mainQuery, "Отчет о выданных регистрационных удостоверениях c {$this->from} по {$this->to}.xlsx", $this->from, $this->to);
    }
}