<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 21.03.19
 * Time: 14:33
 */

namespace app\modules\admin\controllers\statistics;

use app\common\models\VisitStatus;
use app\models\db\VisitsGovServices;
use app\modules\admin\controllers\AdminController;
use app\modules\admin\models\export\ServicesReportExport;
use yii\db\Expression;

class ServicesReportController extends AdminController
{
    public $from;
    public $to;
    public $organizations;
    public $areas;
    public $districts;
    public $types;
    public $channels;

    public function init()
    {
        $this->from = \Yii::$app->request->get('from');
        $this->to = \Yii::$app->request->get('to');
        $this->organizations = \Yii::$app->request->get('id_organization', []);
        $this->areas = \Yii::$app->request->get('id_area', []);
        $this->districts = \Yii::$app->request->get('id_district', []);
        $this->types = \Yii::$app->request->get('type_id', []);
        $this->channels = \Yii::$app->request->get('channel', []);

        if (empty($this->from)) {
            $this->from = date("Y") . '-01-01';
        }
        if (empty($this->to)) {
            $this->to = date('Y-m-d');
        }

        parent::init(); // TODO: Change the autogenerated stub
    }

    public function buildQuery($from, $to, $organizations, $areas, $districts, $types, $channels) {
        $fromQuery = VisitsGovServices::find()
            ->select([
                'visits_gov_services.id_service',
                'service_types.id as type_id',
                'service_types.name as type_name',
                'gov_services.name',
                'service_types.id',
                'service_types.name as type_name',
                'id_organization',
                'organizations.short_name',
                'fias_addresses.id_area',
                'fias_addresses.id_district',
                new Expression('"areas"."name" as area'),
                new Expression('"districts"."name" as dist'),
                'visits.channel',
                'visits.source',
                new Expression('sum(coalesce(count, 1)) as sum'),
                'visits_gov_services.price',
                new Expression('sum(coalesce(count, 1)) * visits_gov_services.price as total_Amount')
            ])
            ->joinWith([
                'service',
                'service.serviceType',
                'visit',
                'visit.owner.fias_addresses',
                'visit.organization',
            ], false)
            ->leftjoin( 'areas', ['areas.id' => new Expression('fias_addresses.id_area')])
            ->leftjoin( 'districts', ['districts.id' => new Expression('fias_addresses.id_district')])
            ->groupBy([
                'gov_services.name',
                'visits_gov_services.id_service',
                'visits.id_organization',
                'fias_addresses.id_area',
                'fias_addresses.id_district',
                'areas.name',
                'districts.name',
                'visits.channel',
                'visits.source',
                'gov_services.id',
                'visits_gov_services.price',
                'fias_addresses.id_district',
                'service_types.id',
                'service_types.name',
                'organizations.short_name',
            ])
            ->orderBy([
                'areas.name' => SORT_ASC,
                'districts.name' => SORT_ASC,
                'visits.id_organization' => SORT_ASC,
                'service_types.name' => SORT_ASC])
            ->andWhere(['between', new Expression('coalesce("visits"."fact_start_dttm"::date, lower("visits"."time_range")::date, "visits"."created_at"::date)'), $from, $to])
            ->andWhere(['visits.status' => VisitStatus::FINISHED]);

        if(!empty($organizations)) {
            $fromQuery->andWhere(['id_organization' => $organizations]);
        }
        if(!empty($areas)) {
            $fromQuery->andWhere(['fias_addresses.id_area' => $areas]);
        }
        if(!empty($districts)) {
            $fromQuery->andWhere(['fias_addresses.id_district' => $districts]);
        }
        if(!empty($types)) {
            $fromQuery->andWhere(['service_types.id' => $types]);
        }
        if (!empty($channels)) {
            $fromQuery->andWhere(['visits.channel' => $channels]);
        }

        $mainQuery =  VisitsGovServices::find()
            ->select([
                't.id_service',
                't.type_id',
                't.type_name',
                't.name',
                't.id_organization',
                't.id_area',
                't.area',
                't.id_district',
                't.dist',
                new Expression('sum(t.sum) as sum'),
                't.price',
                new Expression('sum(t.total_amount) as total_amount'),
                't.short_name'
            ])
            ->from(['t' => $fromQuery])
            ->groupBy([
                't.name',
                't.id_organization',
                't.id_area',
                't.area',
                't.id_district',
                't.dist',
                't.id_service',
                't.price',
                't.type_id',
                't.type_name',
                't.short_name'
            ])
            ->orderBy([
                't.area' => SORT_ASC,
                't.dist' => SORT_ASC,
                't.short_name' => SORT_ASC,
                't.type_name' => SORT_ASC])
            ->asArray();

        $mainQuery = $mainQuery->all();
        return $mainQuery;
    }

    public function actionIndex()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas, $this->districts, $this->types, $this->channels);
        return $this->render('index', [
            'data' => $mainQuery
        ]);
    }

    public function actionExport()
    {
        $mainQuery = $this->buildQuery($this->from, $this->to, $this->organizations, $this->areas, $this->districts, $this->types, $this->channels);
        $exportedReport = new ServicesReportExport();
        $exportedReport->export($mainQuery, "Отчет по контролю спроса c {$this->from} по {$this->to}.xls", $this->from, $this->to);
    }
}