<?php

namespace app\models\db\tmc;

use app\common\validators\FullTrimValidator;
use app\models\db\ActiveRecord;
use app\models\db\Diseases;
use app\models\db\Measures;
use app\models\db\Species;
use yii\base\BaseObject;

/**
 * This is the model class for table "dosages".
 *
 * @property int $id
 * @property int $age_range
 * @property int $weight_range
 * @property string $dosage
 * @property int $id_tmc
 * @property int $id_species
 * @property int $id_disease
 * @property int $id_measure
 * @property int $type_tmc
 * @property string $name
 * @property string $pet_size
 * @property string $is_default
 * @property TmcBase $tmc
 * @property Measures $measure
 * @property Diseases $disease
 * @property Species $species
 * @property DosagesFlags $flag
 */
class Dosages extends ActiveRecord
{
    const ALLOWED_TYPES_TMC = [
        TmcBase::TYPE_DRUG,
        TmcBase::TYPE_VACCINE
    ];

    /**
     * Размер животных
     */
    const PET_SIZE_SMALL = 'small'; //мелкое
    const PET_SIZE_LARGE = 'large'; //крупное

    /**
     * @var string[]
     */
    public static $petSizeCollection = [
        self::PET_SIZE_SMALL,
        self::PET_SIZE_LARGE,
    ];

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'tmc.dosages';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            // NAME
            [['name', 'pet_size'], 'required'],
            [['name'], 'string', 'max' => 50],
            [['name'], FullTrimValidator::class],

            [['dosage', 'id_tmc', 'id_measure', 'weight_range', 'id_species', 'id_disease', 'type_tmc'], 'required'],
            [['created_by', 'updated_by'], 'default', 'value' => null],
            [['age_range', 'weight_range'], 'string'],
            [
                [
                    'id_tmc',
                    'id_measure',
                    'id_species',
                    'id_disease',
                    'created_by',
                    'updated_by'
                ],
                'integer'
            ],
            [
                ['type_tmc'],
                'in',
                'range'       => self::ALLOWED_TYPES_TMC,
                'strict'      => true,
                'skipOnEmpty' => false,
                'skipOnError' => false
            ],
            [['dosage'], 'number', 'min' => 1],
            [['pet_size'], 'in', 'range' => self::$petSizeCollection],
            [['is_default'], 'boolean'],
            //[['is_default'], 'unique', 'filter' => ['id_tmc' => $this->getAttribute('id_tmc')]],
            [['created_at', 'updated_at'], 'safe'],
            [
                ['id_tmc'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => TmcBase::class,
                'targetAttribute' => ['id_tmc' => 'id']
            ],
            [
                ['id_disease'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => Diseases::class,
                'targetAttribute' => ['id_disease' => 'id']
            ],
            [
                ['id_species'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => Species::class,
                'targetAttribute' => ['id_species' => 'id']
            ],
            [
                ['id_measure'],
                'exist',
                'skipOnError'     => true,
                'targetClass'     => Measures::class,
                'targetAttribute' => ['id_measure' => 'id']
            ],

        ];
    }

    public function attributeLabels()
    {
        return [
            'name'        => 'Название для дозировки',
            'age_from'    => 'Возраст с',
            'age_to'      => 'Возраст по',
            'weight_from' => 'Вес с',
            'weight_to'   => 'Вес по',
            'dosage'      => 'Дозировка',
            'id_species'  => 'Вид животного',
            'id_disease'  => 'Заболевание',
            'id_tmc'      => 'Препарат',
            'id_measure'  => 'Единица измерения',
            'pet_size'    => 'Размер животного',
            'is_default'  => 'Дозировка по умолчанию',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        if($insert) {
            $this->insertDosagesFlags();
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

    /**
     * Создает (привязывает) новую сущность флагов дозирочки в БД при создании новой сущности
     */
    private function insertDosagesFlags()
    {
        $dosageFlag = new DosagesFlags([
            'for_act' => false,
        ]);
        $dosageFlag->save();

        $this->link('flag', $dosageFlag);
        $this->setFlagsDefault();
    }

    /**
     *  Установка флагов по умолчанию
     */
    private function setFlagsDefault()
    {
        //Если для одного ТМЦ существует только одна дозировка - ставим флаг "для актов"
        if (Dosages::find()->where(['id_tmc' => $this->id_tmc])->count() === 1) {
            $this->flag->setAttribute('for_act', true)->save();
        }
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTmc()
    {
        return $this->hasOne(TmcBase::class, ['id' => 'id_tmc', 'type' => 'type_tmc']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMeasure()
    {
        return $this->hasOne(Measures::class, ['id' => 'id_measure']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSpecies()
    {
        return $this->hasOne(Species::class, ['id' => 'id_species']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDisease()
    {
        return $this->hasOne(Diseases::class, ['id' => 'id_disease']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFlag()
    {
        return $this->hasOne(DosagesFlags::class, ['id_dosages' => 'id']);
    }

}
