<?php

return [
    // Журнал биохимического исследования крови
    [
        'label' => '№ п/п',
        'prop_path' => 'NPP',
        'prop_type' => 'string',
    ],
    [
        'label' => 'Дата поступления',
        'prop_path' => 'P3_Visitstartdate',
        'prop_type' => 'datetime',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => '№ экспертизы',
        'prop_path' => 'P2_SerialServiceNum',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Наименование владельца',
        'prop_path' => 'P4_Ownername',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Адрес владельца',
        'prop_path' => 'P5_Owneraddres',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Номер пробы',
        'prop_path' => 'P0_Venousbloodanalysisnum',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Вид животного',
        'prop_path' => 'P6_Speciesname',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Возраст',
        'prop_path' => 'P10_Petbirthday',
        'prop_type' => 'datetime',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Пол животного',
        'prop_path' => 'P8_Petsex',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'билирубин общий (мкмоль/л)',
        'prop_path' => 'P14_Totalbilirubinmcmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'билирубин прямой (мкмоль/л)',
        'prop_path' => 'P18_Conjugatedbilirubinmcmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'АЛТ аланинаминотрансфераза',
        'prop_path' => 'P22_Altalanniamvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'АСТ аспартатаминотрансфераза',
        'prop_path' => 'P24_Astaspartvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'ά- амилаза',
        'prop_path' => 'P36_Amilazavalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Щелочная фосфатаза',
        'prop_path' => 'P34_Shelochfosfatvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'мочевина (ммоль/л)',
        'prop_path' => 'P26_Mochevinammvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'креатинин (мкмоль/л)',
        'prop_path' => 'P30_Creatininemcmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Холестерол (ммоль/л)',
        'prop_path' => 'P50_Holestermmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Триглицериды (ммоль/л)',
        'prop_path' => 'P54_Triglyceridsmmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'глюкоза (мкмоль/л)',
        'prop_path' => 'P40_Glukozamcmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Кетоновые тела',
        'prop_path' => 'P104_Ketonebodiesvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Бикарботаны',
        'prop_path' => 'P105_Bikarbonatvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Общий белок (г/л)',
        'prop_path' => 'P94_Totalproteinglvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'кальций (ммоль/л)',
        'prop_path' => 'P70_Calciummmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'фосфор (ммоль/л)',
        'prop_path' => 'P66_Phosphormmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'калий (ммоль/л)',
        'prop_path' => 'P58_Caliummmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'натрий (ммоль/л)',
        'prop_path' => 'P62_Natrmmvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Белковые фракции',
        'prop_path' => 'P106_Proteinfractionsvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Заключение',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Дата выдачи ответа',
        'prop_path' => null,
        'prop_type' => 'datetime',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Подпись врача',
        'prop_path' => null,
        'prop_type' => 'string',
    ],
];
