<?php

return [
    // Журнал гематологических исследований
    [
        'label' => '№ п/п',
        'prop_path' => 'NPP',
        'prop_type' => 'string',
    ],
    [
        'label' => 'Дата',
        'prop_path' => 'P3_Visitstartdate',
        'prop_type' => 'datetime',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => '№ экспертизы',
        'prop_path' => 'P2_SerialServiceNum',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Кем направлен',
        'prop_path' => 'P33_SpecialistFIO',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Владелец животного',
        'prop_path' => 'P4_Ownername',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Адрес владельца',
        'prop_path' => 'P5_Owneraddres',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Вид животного',
        'prop_path' => 'P6_Speciesname',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Возраст животного',
        'prop_path' => 'P10_Petbirthday',
        'prop_type' => 'datetime',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'Кличка животного',
        'prop_path' => 'P9_Petname',
        'prop_type' => 'string',
        'param_type' => 'visit_param_value',
    ],
    [
        'label' => 'НВ (g/l)',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'В 1 кубич. мм, эритроцит (10¹²/l)',
        'prop_path' => 'P14_Wbcvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'В 1 кубич. мм, лейкоцит (10⁹/l)',
        'prop_path' => 'P22_Rbcvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'HCT (l/l)',
        'prop_path' => 'P26_Hctvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'MCV (fl)',
        'prop_path' => 'P28_Mcvvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'MCH (pg)',
        'prop_path' => 'P30_Mchvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'MCHC (g/l)',
        'prop_path' => 'P32_Mchcvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'PLT (10⁹/l)',
        'prop_path' => 'P36_Pltvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'LYM (10⁹/l)',
        'prop_path' => 'P16_Lymvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'MON (10⁹/l)',
        'prop_path' => 'P18_Monvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'GRA (10⁹/l)',
        'prop_path' => 'P20_Gravalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'RDW (%)',
        'prop_path' => 'P34_Rdwvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'MPV (fl)',
        'prop_path' => 'P38_Mpvvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'PCT (cl/l)',
        'prop_path' => 'P40_Pctvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'PDW (%)',
        'prop_path' => 'P42_Pdwvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'СОЭ (мм/час), 15 м',
        'prop_path' => 'P44_Soevalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'СОЭ (мм/час), 30 м',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'СОЭ (мм/час), 45 м',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'СОЭ (мм/час), 60 м',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'СОЭ (мм/час), 24 ч',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), Б',
        'prop_path' => 'P56_Bazophilvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), Э',
        'prop_path' => 'P52_Eosinophilsvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), Ми',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), Ю',
        'prop_path' => 'P46_Youngvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), П',
        'prop_path' => 'P48_Palochkoyadervalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), С',
        'prop_path' => 'P50_Segmentvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), Л',
        'prop_path' => 'P58_Limphocitvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), ГП',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Лейкоцитарная формула (%), Мо',
        'prop_path' => 'P54_Monocitvalue',
        'prop_type' => 'string',
        'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Кровепаразиты',
        'prop_path' => null,
        'prop_type' => 'string',
        // 'param_type' => 'visit_service_param_value',
    ],
    [
        'label' => 'Дата ответа',
        'prop_path' => null,
        'prop_type' => 'string',
    ],
    [
        'label' => 'Подпись ветврача',
        'prop_path' => null,
        'prop_type' => 'string',
    ],
];
